### ISSUE TITLE
SCIM APIs not protected by default

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans-scim#2]
Describe the bug
When SCIM is used, SCIM APIs are not protected by default allowing anyone to create, update, delete Users.

To Reproduce

    Install Jans
    Execute GET call to https:///jans-scim/restv1/v2/Users

Expected behavior
I would expect access to SCIM API access to be protected by default similar to Config API.

**Comment by jgomer2001** [comment]
These 2 earlier commits broke the protection:

https://github.com/JanssenProject/jans-scim/commit/06a878894d10a827af3e7ba1a7fa4c2fdfc55de4
https://github.com/JanssenProject/jans-scim/commit/d409d320a98707eb7b0a8497396be0d7ae852ff1

**Comment by jgomer2001** [comment]
war with fix available at https://maven.jans.io/maven/io/jans/jans-scim-server/1.0.0-SNAPSHOT/
