### ISSUE TITLE
Remove UMA and test mode for SCIM

### ISSUE THREAD

**Issue by jgomer2001** [JanssenProject/jans-scim#3]
> SCIM will use a new protection mechanism similar to test mode. UMA will be removed

**Comment by jgomer2001** [comment]
Added scopes to swagger docs
https://github.com/JanssenProject/jans-scim/commit/2a4511f5edbcd9d2c41120e7392857e0950a57ca

**Comment by nynymike** [comment]
I don't think you need to remove test mode.

**Comment by yurem** [comment]
Current code not uses UMA
